name: "Deploy Estuary Flow (CDC-only)"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  ESTUARY_API_KEY:    ${{ secrets.ESTUARY_API_KEY }}
  SQLSERVER_HOST:    ${{ secrets.SQLSERVER_HOST }}
  SQLSERVER_PORT:    ${{ secrets.SQLSERVER_PORT }}
  SQLSERVER_DATABASE: ${{ secrets.SQLSERVER_DATABASE }}
  SQLSERVER_USERNAME: ${{ secrets.SQLSERVER_USERNAME }}
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER:    ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
  SNOWFLAKE_ROLE:     ${{ secrets.SNOWFLAKE_ROLE }}

jobs:
  deploy:
    name: "Test & Deploy Estuary Specs"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        # Pin to v4 instead of a SHA to prevent 404 errors :contentReference[oaicite:23]{index=23}

      - name: "Install flowctl CLI"
        run: |
          sudo curl -L \
            https://github.com/estuary/flow/releases/latest/download/flowctl-x86_64-linux \
            -o /usr/local/bin/flowctl && sudo chmod +x /usr/local/bin/flowctl
            
        # Ensures we have the latest flowctl binary :contentReference[oaicite:24]{index=24}
      - name: Debug Print token length
        run: |
          echo "Token length: $(echo -n \${{ secrets.ESTUARY_API_KEY }} | wc -c)"
      # flowctl auth token --token ${{ secrets.ESTUARY_API_KEY }}
      - name: "Authenticate to Estuary Flow"
        run: |
          flowctl auth token --token eyJhbGciOiJIUzI1NiIsImtpZCI6IlhaYXZsWHkrajczYUxwYlEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2V5cmNubXV6enlyaXlwZGFqd2RrLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJiMjQ2MzZjZi03OGQwLTRkZTQtOTFjYi1mODQ1ZWVmNDExNjgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ4NzI2Mzc5LCJpYXQiOjE3NDg3MjI3NzksImVtYWlsIjoiYWRkeWNsZW1lbnRAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJnb29nbGUiLCJwcm92aWRlcnMiOlsiZ29vZ2xlIl19LCJ1c2VyX21ldGFkYXRhIjp7ImF2YXRhcl91cmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NJTHYtYUd1S0lTdjBUMVZacHd2a1FRWGlENW1QZUFHVUtoT1NsOU5rSUpXbXVoc1E9czk2LWMiLCJlbWFpbCI6ImFkZHljbGVtZW50QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmdWxsX25hbWUiOiJBZGR5IENsZW1lbnQiLCJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYW1lIjoiQWRkeSBDbGVtZW50IiwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jSUx2LWFHdUtJU3YwVDFWWnB3dmtRUVhpRDVtUGVBR1VLaE9TbDlOa0lKV211aHNRPXM5Ni1jIiwicHJvdmlkZXJfaWQiOiIxMDY2Njk1MzMyNjcwMjMwODU3NjAiLCJzdWIiOiIxMDY2Njk1MzMyNjcwMjMwODU3NjAifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvYXV0aCIsInRpbWVzdGFtcCI6MTc0ODcxMTA2Mn1dLCJzZXNzaW9uX2lkIjoiZWJjOGFjNDAtOTAyMC00NTRkLTk4NTktMmY2YmZmYjk0NjM0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.ltQzvBReaLCEFpQ-D_SxpbhdfUVjchVVvkh1g6wBH1I
          flowctl auth verify

      - name: "Validate All Specs Together"
        run: |
          flowctl catalog test --source .estuary/flow.yaml


      - name: "Sync Resources to Estuary Flow"
        run: |
          flowctl sync .estuary/snowflake-materialization.yaml
          flowctl sync .estuary/sqlserver-capture.yaml
          flowctl sync .estuary/flow-binding.yaml
        # Publishes validated specs to Flow 

      - name: "Confirm Resource Creation"
        run: |
          flowctl get capture   | grep loandataservices/sqlserver-capture || true
          flowctl get materialization | grep loandataservices/snowflake-materialization || true
          flowctl get flow      | grep mssql-to-snowflake-cdc-flow || true
        # Verifies the capture, materialization, and flow exist in Flow. 
